name: git_watcher
description: Application for working with Github REST API.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/